name = "mako-secretary"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "マコ-秘書-DB"
database_id = "a2d2049d-3d80-424d-90d8-451f2341adf3"
